"""Fix ProgramMachine

Revision ID: 7b2987cfdecc
Revises: d64db1412fa2
Create Date: 2024-04-01 13:15:56.746895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2987cfdecc'
down_revision: Union[str, None] = 'd64db1412fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_machine', sa.Column('knees', sa.String(length=50), nullable=True))
    op.drop_column('program_machine', 'кnees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_machine', sa.Column('кnees', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('program_machine', 'knees')
    # ### end Alembic commands ###
