"""coach added EMAIL

Revision ID: 7b5d465efd3d
Revises: daa422a7bad8
Create Date: 2024-03-19 03:54:00.293357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5d465efd3d'
down_revision: Union[str, None] = 'daa422a7bad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach', 'email')
    # ### end Alembic commands ###
