"""coach added home and mobile phones

Revision ID: a01d3f773129
Revises: ed0eb216ef5d
Create Date: 2024-03-18 02:50:38.759484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01d3f773129'
down_revision: Union[str, None] = 'ed0eb216ef5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('work_phone', sa.String(), nullable=True))
    op.add_column('coach', sa.Column('mobile_phone', sa.String(), nullable=True))
    op.drop_column('program', 'is_delete')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('coach', 'mobile_phone')
    op.drop_column('coach', 'work_phone')
    # ### end Alembic commands ###
