"""Add weight and height fields to trainee table

Revision ID: a4eb53f3aded
Revises: 8c11da2b6257
Create Date: 2025-07-04 18:31:26.097548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4eb53f3aded"
down_revision: Union[str, None] = "8c11da2b6257"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trainee", sa.Column("weight", sa.Float(), nullable=True))
    op.add_column("trainee", sa.Column("height", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trainee", "height")
    op.drop_column("trainee", "weight")
    # ### end Alembic commands ###
