"""added fields thighs and grip

Revision ID: b53f8cdfbae6
Revises: 7b2987cfdecc
Create Date: 2024-04-25 14:26:24.387406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53f8cdfbae6'
down_revision: Union[str, None] = '7b2987cfdecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_machine', sa.Column('thighs', sa.String(length=50), nullable=True))
    op.add_column('program_machine', sa.Column('grip', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_machine', 'grip')
    op.drop_column('program_machine', 'thighs')
    # ### end Alembic commands ###
