"""Fix Program and ProgramMachine

Revision ID: d64db1412fa2
Revises: 64a976fbcf32
Create Date: 2024-03-31 14:16:13.519503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d64db1412fa2"
down_revision: Union[str, None] = "64a976fbcf32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "program",
        sa.Column("is_delete", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column("program", sa.Column("workout_date", sa.DateTime(), nullable=True))
    op.add_column(
        "program_machine", sa.Column("кnees", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "program_machine", sa.Column("legs", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "program_machine", sa.Column("for_two_legs", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "program_machine", sa.Column("chest", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "program_machine", sa.Column("angal", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "program_machine", sa.Column("note", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("program_machine", "note")
    op.drop_column("program_machine", "angal")
    op.drop_column("program_machine", "chest")
    op.drop_column("program_machine", "for_two_legs")
    op.drop_column("program_machine", "legs")
    op.drop_column("program_machine", "кnees")
    op.drop_column("program", "workout_date")
    op.drop_column("program", "is_delete")
    # ### end Alembic commands ###
