"""coach added note

Revision ID: daa422a7bad8
Revises: a01d3f773129
Create Date: 2024-03-19 03:31:28.697117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa422a7bad8'
down_revision: Union[str, None] = 'a01d3f773129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('note', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach', 'note')
    # ### end Alembic commands ###
