"""prorgram added is_delete

Revision ID: ed0eb216ef5d
Revises: 9c847e83e7a7
Create Date: 2024-03-14 23:15:18.537928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed0eb216ef5d"
down_revision: Union[str, None] = "9c847e83e7a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "program",
        sa.Column("is_delete", sa.Boolean(), nullable=False, server_default="false"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("program", "is_delete")
    # ### end Alembic commands ###
